// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Product Service",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "successful API Response",
            "schema": {
              "$ref": "#/definitions/Product"
            }
          },
          "404": {
            "description": "error API Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "summary": "createProduct",
        "description": "",
        "operationId": "createProduct.post.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Product"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful API Response",
            "schema": {
              "$ref": "#/definitions/PostProduct"
            }
          },
          "404": {
            "description": "error API Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/products/{id}": {
      "get": {
        "summary": "getProductsById",
        "description": "",
        "operationId": "getProductsById.get.products/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "successful API Response",
            "schema": {
              "$ref": "#/definitions/Product"
            }
          },
          "404": {
            "description": "error API Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Product": {
      "properties": {
        "id": {
          "title": "Product.id",
          "type": "string"
        },
        "title": {
          "title": "Product.title",
          "type": "string"
        },
        "description": {
          "title": "Product.description",
          "type": "string"
        },
        "price": {
          "title": "Product.price",
          "type": "number"
        },
        "count": {
          "title": "Product.count",
          "type": "number"
        }
      },
      "required": [
        "id",
        "title",
        "description",
        "price",
        "count"
      ],
      "additionalProperties": false,
      "title": "Product",
      "type": "object"
    },
    "PostProduct": {
      "properties": {
        "message": {
          "title": "PostProduct.message",
          "type": "string"
        },
        "product": {
          "$ref": "#/definitions/Product",
          "title": "PostProduct.product"
        }
      },
      "required": [
        "message",
        "product"
      ],
      "additionalProperties": false,
      "title": "PostProduct",
      "type": "object"
    },
    "Error": {
      "properties": {
        "error": {
          "title": "Error.error",
          "type": "string"
        }
      },
      "required": [
        "error"
      ],
      "additionalProperties": false,
      "title": "Error",
      "type": "object"
    },
    "Stocks": {
      "properties": {
        "id": {
          "title": "Stocks.id",
          "type": "string"
        },
        "product_id": {
          "title": "Stocks.product_id",
          "type": "string"
        },
        "count": {
          "title": "Stocks.count",
          "type": "number"
        }
      },
      "required": [
        "id",
        "product_id",
        "count"
      ],
      "additionalProperties": false,
      "title": "Stocks",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev"
};