// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Authorization Service",
    "version": "1"
  },
  "paths": {},
  "definitions": {
    "Error": {
      "properties": {
        "error": {
          "title": "Error.error",
          "type": "string"
        }
      },
      "required": [
        "error"
      ],
      "additionalProperties": false,
      "title": "Error",
      "type": "object"
    },
    "Policy": {
      "properties": {
        "principalId": {
          "title": "Policy.principalId",
          "type": "string"
        },
        "policyDocument": {
          "properties": {
            "Version": {
              "title": "Policy.policyDocument.Version",
              "type": "string"
            },
            "Statement": {
              "items": [
                {
                  "properties": {
                    "Action": {
                      "title": "Policy.policyDocument.Statement.0.Action",
                      "type": "string"
                    },
                    "Effect": {
                      "title": "Policy.policyDocument.Statement.0.Effect",
                      "type": "string"
                    },
                    "Resource": {
                      "title": "Policy.policyDocument.Statement.0.Resource",
                      "type": "string"
                    }
                  },
                  "required": [
                    "Action",
                    "Effect",
                    "Resource"
                  ],
                  "additionalProperties": false,
                  "title": "Policy.policyDocument.Statement.0",
                  "type": "object"
                }
              ],
              "additionalItems": false,
              "minItems": 1,
              "title": "Policy.policyDocument.Statement",
              "type": "array"
            }
          },
          "required": [
            "Version",
            "Statement"
          ],
          "additionalProperties": false,
          "title": "Policy.policyDocument",
          "type": "object"
        }
      },
      "required": [
        "principalId",
        "policyDocument"
      ],
      "additionalProperties": false,
      "title": "Policy",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev"
};