// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Import Service",
    "version": "1"
  },
  "paths": {
    "/import": {
      "get": {
        "summary": "importProductsFile",
        "description": "",
        "operationId": "importProductsFile.get.import",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "name",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful API Response",
            "schema": {
              "$ref": "#/definitions/File"
            }
          },
          "404": {
            "description": "error API Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "File": {
      "properties": {
        "url": {
          "title": "File.url",
          "type": "string"
        }
      },
      "required": [
        "url"
      ],
      "additionalProperties": false,
      "title": "File",
      "type": "object"
    },
    "Error": {
      "properties": {
        "error": {
          "title": "Error.error",
          "type": "string"
        }
      },
      "required": [
        "error"
      ],
      "additionalProperties": false,
      "title": "Error",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev"
};